### ISSUE TITLE
Build with Spack HDF1.14 causes namespace errors

### ISSUE THREAD

**Issue by matt-graham** [ExCALIBUR-NEPTUNE/NESO-Particles#37]
On trying to install NESO using Spack in a clean `spack/ubuntu-jammy` Docker container following the instructions [here](https://github.com/ExCALIBUR-NEPTUNE/NESO#building-with-spack) (other than pinning `intel-oneapi-compilers` package version to 2022.1.0 to avoid [this issue](https://github.com/ExCALIBUR-NEPTUNE/NESO/issues/183)) the build of `neso-particles` with GCC 11.3 fails with a series of namespace related errors: 

```
/usr/include/c++/11/cinttypes:58:11: error: 'imaxdiv_t' has not been declared in '::'
   58 |   using ::imaxdiv_t;
/usr/include/c++/11/cinttypes:61:11: error: 'imaxabs' has not been declared in '::'
   61 |   using ::imaxabs;
/usr/include/c++/11/cinttypes:62:11: error: 'imaxdiv' has not been declared in '::'
   62 |   using ::imaxdiv;
/usr/include/c++/11/cinttypes:68:11: error: 'strtoimax' has not been declared in '::'
   68 |   using ::strtoimax;
/usr/include/c++/11/cinttypes:69:11: error: 'strtoumax' has not been declared in '::'
   69 |   using ::strtoumax;
/usr/include/c++/11/cinttypes:72:11: error: 'wcstoimax' has not been declared in '::'
   72 |   using ::wcstoimax;
/usr/include/c++/11/cinttypes:73:11: error: 'wcstoumax' has not been declared in '::'
   73 |   using ::wcstoumax;
/root/NESO/neso-particles/include/particle_io.hpp:21:8: error: 'string' in namespace 'NESO::Particles::std' does not name a type
   21 |   std::string filename;
/root/NESO/neso-particles/include/particle_io.hpp:28:8: error: 'string' in namespace 'NESO::Particles::std' does not name a type
   28 |   std::string position_labels[3] = {"x", "y", "z"};
/root/NESO/neso-particles/include/particle_io.hpp:194:21: error: expected ')' before 'filename'
  194 |   H5Part(std::string filename, ParticleGroupSharedPtr particle_group, T... args)

...
```

I get the same errors when trying to install with Spack using GCC 10.3 directly on my Ubuntu 20.04 system. 

The first series of `* has not been declared in '::'` errors seem to arise from an include in a header file `H5public.h` which is itself included from `hdf5.h` and some of the latter errors also seems to relate to HDF5 types / objects so I'm not sure if this is some upstream issue with the `hdf5` Spack package version that is getting picked up (`hdf5-1.14.1-2`).

As the Git submodule reference in `NESO` points to [c63f79d](https://github.com/ExCALIBUR-NEPTUNE/NESO-Particles/commit/c63f79dbc3d29691eb1d35b6c0d16a19246ccf01) it's possible this has been fixed on `main` if it a problem on the `NESO-Particles` side (I wasn't sure if this issue should be tracked here or the main NESO repository - feel free to transfer).

Apologies if there  something obvious I'm doing wrong here or that is needed to fix this. This is my first time using Spack and my attempts to diagnose and fix the errors myself haven't gotten anywhere!

<details>
<summary>Dockerfile to reproduce</summary>

```
FROM spack/ubuntu-jammy:latest
ENV NESO_ROOT=/root/NESO
RUN spack install intel-oneapi-compilers@2022.1.0 && \
    spack load intel-oneapi-compilers && \
    spack compiler find && \
    spack unload intel-oneapi-compilers
RUN git clone --recurse-submodules -j4 https://github.com/ExCALIBUR-NEPTUNE/NESO.git $NESO_ROOT
WORKDIR $NESO_ROOT
RUN . activate && spack install
```
</details>

<details>
<summary> Error output from Spack for `neso-particles` install stage (truncated to fit into issue comment character limit)</summary>

```
==> Installing neso-particles-working-s6umyaaliectjpdxwmr7okgikpn7ovzl [116/118]
==> No binary for neso-particles-working-s6umyaaliectjpdxwmr7okgikpn7ovzl found: installing from source
==> No patches needed for neso-particles
==> neso-particles: Executing phase: 'cmake'
==> neso-particles: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    '/opt/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/gmake-4.4.1-xgnqusnc3orrautjhhmz7wa73nr7vyts/bin/make' '-j8'

372 errors found in build log:
     132     cd /root/NESO/neso-particles/spack-build-s6umyaa/test && /opt/spac
             k/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/hipsycl-0.9.4-7tf
             ch4qrqrmhfinf4w5yb2eu4icie5c3/lib/cmake/hipSYCL/syclcc-launcher --
             launcher-cxx-compiler=/opt/spack/lib/spack/env/gcc/g++ --launcher-
             syclcc=/opt/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/h
             ipsycl-0.9.4-7tfch4qrqrmhfinf4w5yb2eu4icie5c3/bin/syclcc-clang  --
             hipsycl-platform=omp /opt/spack/lib/spack/env/gcc/g++ -DGPU_SELECT
             OR=0 -DGTEST_LINKED_AS_SHARED_LIBRARY=1 -DH5_BUILT_AS_DYNAMIC_LIB
             -DNESO_PARTICLES_DEVICE_TYPE_CPU -DNESO_PARTICLES_HDF5 -D_FILE_OFF
             SET_BITS=64 -D_GNU_SOURCE -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURC
             E -D_POSIX_C_SOURCE=200809L -I/root/NESO/neso-particles/include -i
             system /opt/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/i
             ntel-oneapi-mpi-2021.10.0-wzxpzgsiyixjgmjct3cwi7sflyo2ect2/mpi/202
             1.10.0/include -isystem /opt/spack/opt/spack/linux-ubuntu22.04-sky
             lake/gcc-11.3.0/intel-oneapi-mpi-2021.10.0-wzxpzgsiyixjgmjct3cwi7s
             flyo2ect2/include -isystem /opt/spack/opt/spack/linux-ubuntu22.04-
             skylake/gcc-11.3.0/hdf5-1.14.1-2-hgrekohrqqra2nwh4sh4wbuy53yniut3/
             include -isystem /opt/spack/opt/spack/linux-ubuntu22.04-skylake/gc
             c-11.3.0/googletest-1.12.1-nwhvujj62xj3ro5hnhctk7u552onqiiu/includ
             e -isystem /opt/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3
             .0/hipsycl-0.9.4-7tfch4qrqrmhfinf4w5yb2eu4icie5c3/include -O3 -DND
             EBUG -std=gnu++17 -MD -MT test/CMakeFiles/test_cell_dat.dir/test_c
             ell_dat.cpp.o -MF CMakeFiles/test_cell_dat.dir/test_cell_dat.cpp.o
             .d -o CMakeFiles/test_cell_dat.dir/test_cell_dat.cpp.o -c /root/NE
             SO/neso-particles/test/test_cell_dat.cpp
     133     In file included from /opt/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/hdf5-1.14.1-2-hgrekohrqqra2nwh4sh4wbuy53yniut3/include/H5public.h:39,
     134                      from /opt/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/hdf5-1.14.1-2-hgrekohrqqra2nwh4sh4wbuy53yniut3/include/hdf5.h:21,
     135                      from /root/NESO/neso-particles/include/particle_io.hpp:14,
     136                      from /root/NESO/neso-particles/include/neso_particles.hpp:22,
     137                      from /root/NESO/neso-particles/test/test_boundary_pbc.cpp:4:
  >> 138     /usr/include/c++/11/cinttypes:58:11: error: 'imaxdiv_t' has not been declared in '::'
     139        58 |   using ::imaxdiv_t;
     140           |           ^~~~~~~~~
  >> 141     /usr/include/c++/11/cinttypes:61:11: error: 'imaxabs' has not been declared in '::'
     142        61 |   using ::imaxabs;
     143           |           ^~~~~~~
  >> 144     /usr/include/c++/11/cinttypes:62:11: error: 'imaxdiv' has not been declared in '::'
     145        62 |   using ::imaxdiv;
     146           |           ^~~~~~~
  >> 147     /usr/include/c++/11/cinttypes:68:11: error: 'strtoimax' has not been declared in '::'
     148        68 |   using ::strtoimax;
     149           |           ^~~~~~~~~
  >> 150     /usr/include/c++/11/cinttypes:69:11: error: 'strtoumax' has not been declared in '::'
     151        69 |   using ::strtoumax;
     152           |           ^~~~~~~~~
  >> 153     /usr/include/c++/11/cinttypes:72:11: error: 'wcstoimax' has not been declared in '::'
     154        72 |   using ::wcstoimax;
     155           |           ^~~~~~~~~
  >> 156     /usr/include/c++/11/cinttypes:73:11: error: 'wcstoumax' has not been declared in '::'
     157        73 |   using ::wcstoumax;
     158           |           ^~~~~~~~~
     159     In file included from /root/NESO/neso-particles/include/neso_particles.hpp:22,
     160                      from /root/NESO/neso-particles/test/test_boundary_pbc.cpp:4:
  >> 161     /root/NESO/neso-particles/include/particle_io.hpp:21:8: error: 'string' in namespace 'NESO::Particles::std' does not name a type
     162        21 |   std::string filename;
     163           |        ^~~~~~
  >> 164     /root/NESO/neso-particles/include/particle_io.hpp:28:8: error: 'string' in namespace 'NESO::Particles::std' does not name a type
     165        28 |   std::string position_labels[3] = {"x", "y", "z"};
     166           |        ^~~~~~
  >> 167     /root/NESO/neso-particles/include/particle_io.hpp:194:21: error: expected ')' before 'filename'
     168       194 |   H5Part(std::string filename, ParticleGroupSharedPtr particle_group, T... args)
     169           |         ~           ^~~~~~~~~
     170           |                     )
     171     /root/NESO/neso-particles/include/particle_io.hpp: In member function 'void NESO::Particles::H5Part::write_dat_column_wise(int64_t, NESO::Particles::BufferHost<char>&, NESO::Particles::ParticleDatSharedPtr<T>, NESO::Particles::hid_t, NESO::Particles::hid_t, NESO::Particles::hid_t, NESO::Particles::hid_t, bool)':
  >> 172     /root/NESO/neso-particles/include/particle_io.hpp:95:12: error: 'string' is not a member of 'NESO::Particles::std'
     173        95 |       std::string name;
     174           |            ^~~~~~
     175     /root/NESO/neso-particles/include/particle_io.hpp:95:12: note: suggested alternatives:
     176     In file included from /usr/include/c++/11/iosfwd:39,
     177                      from /usr/include/c++/11/bits/shared_ptr.h:52,
     178                      from /usr/include/c++/11/memory:77,

     ...

     191                      from /root/NESO/neso-particles/test/test_boundary_pbc.cpp:1:
     192     /usr/include/c++/11/string:67:11: note:   'std::pmr::string'
     193        67 |     using string    = basic_string<char>;
     194           |           ^~~~~~
     195     In file included from /root/NESO/neso-particles/include/neso_particles.hpp:22,
     196                      from /root/NESO/neso-particles/test/test_boundary _pbc.cpp:4:
  >> 197     /root/NESO/neso-particles/include/particle_io.hpp:97:9: error: 'name' was not declared in this scope
     198        97 |         name = this->position_labels[cx];
     199           |         ^~~~
     200     /root/NESO/neso-particles/include/particle_io.hpp:97:9: note: suggested alternatives:
     201     In file included from /opt/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/hipsycl-0.9.4-7tfch4qrqrmhfinf4w5yb2eu4icie5c3/include/hipSYCL/sycl/info/info.hpp:35,
     202                      from /opt/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/hipsycl-0.9.4-7tfch4qrqrmhfinf4w5yb2eu4icie5c3/include/hipSYCL/sycl/device.hpp:38,
     203                      from /opt/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/hipsycl-0.9.4-7tfch4qrqrmhfinf4w5yb2eu4icie5c3/include/hipSYCL/sycl/buffer.hpp:51,

     ...

```
</details>

**Comment by cmacmackin** [comment]
What version of HDF5 has been installed? Could you please post the output of `spack find -v hdf5`.

**Comment by matt-graham** [comment]
> Could you try fixing it to version 1.12.2 and see if it builds any better with that? We'll want to make it work with more recent versions too but trying with the old one can help us understand the nature of the problem.

Not sure if this was the correct way to go about this but I reran `spack install` with updated `specs` in `spack.yaml`

```YAML
  specs:
  - neso%oneapi ^nektar%oneapi ^intel-oneapi-mpi ^intel-oneapi-mkl ^py-numpy%intel
    ^boost%intel ^py-cython%oneapi ^dpcpp ^scotch@6 ^hdf5@1.12.2
  - neso%gcc ^openblas ^hipsycl ^scotch@6 ^hdf5@1.12.2
```

This does appear to have fixed the above issue with building `neso-particles` package as that build step now completes successfully 🎉. Unfortunately I now get a different series of errors in the subsequent `neso` build step 😅 but will open a new issue in NESO repository for those.

**Comment by cmacmackin** [comment]
Yes, that's the right way to pin the package version. I'll keep an eye for your next issue.

**Comment by matt-graham** [comment]
I've added details of errors I'm now getting to the previous issue I'd raised for problems with Intel oneAPI build on NESO repository (https://github.com/ExCALIBUR-NEPTUNE/NESO/issues/202#issuecomment-1673189299), though it is also occurring for GCC build. I'm happy to close this issue now unless you want to keep it open for tracking longer term fix.

**Comment by cmacmackin** [comment]
Leave it open. I've changed the name to reflect the underlying issue.

**Comment by cmacmackin** [comment]
This was fixed by #47.
